package com.fang.entity;

public class Classes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.c_id
     *
     * @mbggenerated Wed Jul 27 10:54:00 CST 2016
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.c_name
     *
     * @mbggenerated Wed Jul 27 10:54:00 CST 2016
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.teacher_id
     *
     * @mbggenerated Wed Jul 27 10:54:00 CST 2016
     */
    private Teacher teacher;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.c_id
     *
     * @return the value of classes.c_id
     *
     * @mbggenerated Wed Jul 27 10:54:00 CST 2016
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.c_id
     *
     * @param cId the value for classes.c_id
     *
     * @mbggenerated Wed Jul 27 10:54:00 CST 2016
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.c_name
     *
     * @return the value of classes.c_name
     *
     * @mbggenerated Wed Jul 27 10:54:00 CST 2016
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.c_name
     *
     * @param cName the value for classes.c_name
     *
     * @mbggenerated Wed Jul 27 10:54:00 CST 2016
     */
    public void setcName(String cName) {
        this.cName = cName;
    }

	public Teacher getTeacher() {
		return teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	@Override
	public String toString() {
		return "Classes [cId=" + cId + ", cName=" + cName + ", teacher=" + teacher + "]";
	}
	
    
}