package com.fang.entity;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_id
     *
     * @mbggenerated Wed Jul 27 10:54:00 CST 2016
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_no
     *
     * @mbggenerated Wed Jul 27 10:54:00 CST 2016
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_price
     *
     * @mbggenerated Wed Jul 27 10:54:00 CST 2016
     */
    private Float orderPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_id
     *
     * @return the value of orders.order_id
     *
     * @mbggenerated Wed Jul 27 10:54:00 CST 2016
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_id
     *
     * @param orderId the value for orders.order_id
     *
     * @mbggenerated Wed Jul 27 10:54:00 CST 2016
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_no
     *
     * @return the value of orders.order_no
     *
     * @mbggenerated Wed Jul 27 10:54:00 CST 2016
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_no
     *
     * @param orderNo the value for orders.order_no
     *
     * @mbggenerated Wed Jul 27 10:54:00 CST 2016
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_price
     *
     * @return the value of orders.order_price
     *
     * @mbggenerated Wed Jul 27 10:54:00 CST 2016
     */
    public Float getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_price
     *
     * @param orderPrice the value for orders.order_price
     *
     * @mbggenerated Wed Jul 27 10:54:00 CST 2016
     */
    public void setOrderPrice(Float orderPrice) {
        this.orderPrice = orderPrice;
    }

	@Override
	public String toString() {
		return "Orders [orderId=" + orderId + ", orderNo=" + orderNo + ", orderPrice=" + orderPrice + "]";
	}
    
    
}